# Generated by Django 5.2.4 on 2025-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_products_name_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
