# Generated by Django 5.2.4 on 2025-08-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='stock',
        ),
    ]
