# Generated by Django 5.2.4 on 2025-08-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_orders_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.users')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
