# Generated by Django 5.2.4 on 2025-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_products_image_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=20),
        ),
    ]
