# Generated by Django 5.2.4 on 2025-10-10 00:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_cart_user_alter_like_user_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
